#!/usr/bin/env bash
# Regenerates Sources/Clayzo/Metal/ShaderSource.swift from Shaders.metal.
#
# Xcode compiles Shaders.metal into the package's default.metallib; SwiftPM's
# own build (`swift build`, `swift test` under Xcode 16, Linux tooling) does
# not know what a .metal file is. The backend therefore also carries the
# source as a string and compiles it at first use when no precompiled library
# is present. A test keeps the two in step.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
{
  echo "// Generated by scripts/embed-shaders.sh from Shaders.metal. Do not edit."
  echo "// The Metal source, for hosts whose build did not compile the .metal file."
  echo 'let shaderSource = #"""'
  cat "$here/Sources/Clayzo/Metal/Shaders.metal"
  echo '"""#'
} > "$here/Sources/Clayzo/Metal/ShaderSource.swift"
echo "ShaderSource.swift regenerated ($(wc -c < "$here/Sources/Clayzo/Metal/Shaders.metal") bytes of source)"
